fipe:
  url-pattern:
    manufacturer: http://fipeapi.appspot.com/api/1/carros/marcas.json
    vehicle: http://fipeapi.appspot.com/api/1/carros/veiculos/%d.json
    model: http://fipeapi.appspot.com/api/1/carros/veiculo/%d/%d.json
    price: http://fipeapi.appspot.com/api/1/carros/veiculo/%d/%d/%s.json

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fipe